//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoFeedback
    {
        public int ID { get; set; }
        public string SessionID { get; set; }
        public string Question1 { get; set; }
        public string txtQuestion1 { get; set; }
        public string Question2 { get; set; }
        public string txtQuestion2 { get; set; }
        public string Question3 { get; set; }
        public string txtQuestion3 { get; set; }
        public string Question4 { get; set; }
        public string txtQuestion4 { get; set; }
        public string Question5 { get; set; }
        public string txtQuestion5 { get; set; }
        public Nullable<int> OverAll { get; set; }
        public string SpecialFeedback { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string SoftwareName { get; set; }
    }
}
