//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs2
    {
        public string EmployeeCode { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public System.DateTime LogDate { get; set; }
        public System.TimeSpan LogTime { get; set; }
        public string Direction { get; set; }
        public string SerialNumber { get; set; }
    }
}
