//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MasterDatabaseEntities : DbContext
    {
        public MasterDatabaseEntities()
            : base("name=MasterDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Master_Requestor> Master_Requestor { get; set; }
        public virtual DbSet<MasterCompany> MasterCompanies { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Logs2> Logs2 { get; set; }
    
        public virtual ObjectResult<sp_HCE_Result> sp_HCE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HCE_Result>("sp_HCE");
        }
    }
}
