//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msgtemplate
    {
        public int M_ID { get; set; }
        public string Template { get; set; }
        public string Action { get; set; }
        public string Region { get; set; }
    }
}
