//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAVIOREntities : DbContext
    {
        public SAVIOREntities()
            : base("name=SAVIOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_HCW_Result> sp_HCW()
        {
            try
            {
                return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HCW_Result>("sp_HCW");
            }
            catch
            {
                return null;
            }
            
        }
    }
}
