//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApproval
    {
        public int App_ID { get; set; }
        public string AppName { get; set; }
        public string Email { get; set; }
        public string AppType { get; set; }
        public string AppStatus { get; set; }
        public string Name_ { get; set; }
        public string Region { get; set; }
    }
}
