//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCouriarHistory
    {
        public int HID { get; set; }
        public Nullable<int> CouriarId { get; set; }
        public string ActionBy { get; set; }
        public string Action { get; set; }
        public string ActionIn { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string UserID { get; set; }
    }
}
