//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public int C_ID { get; set; }
        public string CName { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public string GST { get; set; }
        public string City { get; set; }
        public string CState { get; set; }
        public string C_Status { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
