//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIN_Out
    {
        public int M_ID { get; set; }
        public string ChallanNmbr { get; set; }
        public string Requestor { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<System.DateTime> RaiseDate { get; set; }
        public string M_Type { get; set; }
        public string S_Type { get; set; }
        public string M_Location { get; set; }
        public string OutFrom { get; set; }
        public string ModeOfTrans { get; set; }
        public string PersoneName { get; set; }
        public Nullable<System.DateTime> SecApproveTime { get; set; }
        public Nullable<System.DateTime> SecINTime { get; set; }
        public Nullable<System.DateTime> HODTime { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string V_Type { get; set; }
        public string Veh_No { get; set; }
        public string Remark { get; set; }
        public string Descriptn { get; set; }
        public string M_Status { get; set; }
        public string Delay { get; set; }
        public string DelayReason { get; set; }
        public string ApprovingHOD { get; set; }
        public string ContactPerson { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> SecurityOutFrom { get; set; }
        public Nullable<System.DateTime> SecurityOutRcv { get; set; }
        public string MRS { get; set; }
    }
}
