//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaterialInward
    {
        public int ID { get; set; }
        public string PO { get; set; }
        public string ITEM { get; set; }
        public string DESCRIPTION { get; set; }
        public string CREATION_DATE { get; set; }
        public string QUANTITY { get; set; }
        public string UNIT_PRICE { get; set; }
        public string UOM { get; set; }
        public string VENDOR_NAME { get; set; }
        public string GST { get; set; }
        public string CONTACT_NUM { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string ADDRESS { get; set; }
    }
}
