//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPass
    {
        public int PassId { get; set; }
        public string PassNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public string GatePassNumber { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
