//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiteDistance
    {
        public int SD_ID { get; set; }
        public string FromSite { get; set; }
        public string ToSite { get; set; }
        public string Distance { get; set; }
    }
}
