//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVisitor
    {
        public int V_ID { get; set; }
        public string V_Name { get; set; }
        public string V_Phone { get; set; }
        public string V_Email { get; set; }
        public string Visitor_ID { get; set; }
        public string V_IDNumber { get; set; }
        public string V_Pic { get; set; }
        public string V_Status { get; set; }
        public Nullable<int> C_ID { get; set; }
        public string V_Type { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
