//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorAcceptance
    {
        public int VA_ID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public string GatePassID { get; set; }
        public Nullable<System.DateTime> AccptGate { get; set; }
        public Nullable<int> Feedback { get; set; }
        public string Flag { get; set; }
    }
}
