//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingLogin
    {
        public int W_ID { get; set; }
        public string UserID { get; set; }
        public string UPassword { get; set; }
        public string S_Location { get; set; }
        public string WStatus { get; set; }
        public string RoleType { get; set; }
        public string Email { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
