//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrumpService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Material
    {
        public int IT_M { get; set; }
        public Nullable<long> ID { get; set; }
        public string Item { get; set; }
        public string Descriptn { get; set; }
        public string UOM { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> RecQty { get; set; }
        public string M_Status { get; set; }
        public string ApproxValue { get; set; }
        public Nullable<long> CurrRec { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Reason { get; set; }
    }
}
