//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrumpService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppoinment
    {
        public int A_ID { get; set; }
        public string GPID { get; set; }
        public string Requestor { get; set; }
        public Nullable<int> Deptment { get; set; }
        public Nullable<int> ComanyID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public string Visitor_Type { get; set; }
        public Nullable<System.DateTime> V_DateFrom { get; set; }
        public string A_Time { get; set; }
        public Nullable<System.DateTime> V_DateTo { get; set; }
        public string Duration { get; set; }
        public string V_Location { get; set; }
        public string Remark { get; set; }
        public string Valid_at { get; set; }
        public string V_Allowed { get; set; }
        public string A_Type { get; set; }
        public Nullable<System.DateTime> RaiseDate { get; set; }
        public Nullable<System.DateTime> V_InDate { get; set; }
        public Nullable<System.DateTime> V_OutDate { get; set; }
        public string Location { get; set; }
        public string V_Status { get; set; }
        public string EntryType { get; set; }
        public string Flag { get; set; }
    }
}
