//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrumpService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<long> PONum { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string GST_No { get; set; }
        public string Contact_Person { get; set; }
        public string Contact_Num { get; set; }
        public string Mode_Of_Transport { get; set; }
        public string validID { get; set; }
        public string Vehicle_Type { get; set; }
        public string Vehicle_No { get; set; }
        public string Driver_Name { get; set; }
        public string Visitor_Name { get; set; }
        public string Visitor_Number { get; set; }
        public string Visitor_Company { get; set; }
        public string Flag { get; set; }
        public string Region { get; set; }
    }
}
