//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrumpService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOItem
    {
        public int POID { get; set; }
        public Nullable<int> PONmbr { get; set; }
        public string Item { get; set; }
        public string Descriptn { get; set; }
        public string UOM { get; set; }
        public string Qty { get; set; }
        public string RecQty { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    }
}
