//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrumpService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrumpEntities : DbContext
    {
        public TrumpEntities()
            : base("name=TrumpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovalHOD> ApprovalHODs { get; set; }
        public virtual DbSet<ExceptionLogger> ExceptionLoggers { get; set; }
        public virtual DbSet<Item_Material> Item_Material { get; set; }
        public virtual DbSet<Msgtemplate> Msgtemplates { get; set; }
        public virtual DbSet<tblAppoinment> tblAppoinments { get; set; }
        public virtual DbSet<tblApproval> tblApprovals { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblIN_Out> tblIN_Out { get; set; }
        public virtual DbSet<tblMaterial> tblMaterials { get; set; }
        public virtual DbSet<tblMaterialInward> tblMaterialInwards { get; set; }
        public virtual DbSet<tblPO> tblPOes { get; set; }
        public virtual DbSet<tblPOItem> tblPOItems { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblSiteDistance> tblSiteDistances { get; set; }
        public virtual DbSet<tblVisitor> tblVisitors { get; set; }
        public virtual DbSet<tblVisitorINOUT> tblVisitorINOUTs { get; set; }
        public virtual DbSet<VendorData> VendorDatas { get; set; }
        public virtual DbSet<VisitorAcceptance> VisitorAcceptances { get; set; }
        public virtual DbSet<VisitType> VisitTypes { get; set; }
        public virtual DbSet<tblSite> tblSites { get; set; }
    }
}
