//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrumpService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorData
    {
        public int VNID { get; set; }
        public string PartyName { get; set; }
        public string PartyAddress { get; set; }
        public string GST { get; set; }
    }
}
