//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrumpService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitType
    {
        public int V_TY { get; set; }
        public string VstTpe { get; set; }
        public string VStatus { get; set; }
    }
}
